openapi: 3.0.0
info:
  title: AI Gourmet Restaurant API
  version: 1.0.0
  description: REST API for restaurant menu, cart, and order management
servers:
  - url: http://localhost:8000
    description: Development server
components:
  schemas:
    MenuItem:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        category:
          type: string
        price:
          type: number
        description:
          type: string
        is_vegetarian:
          type: boolean
        is_vegan:
          type: boolean
        is_gluten_free:
          type: boolean
        allergens:
          type: array
          items:
            type: string
    CartItem:
      type: object
      properties:
        item_id:
          type: string
        name:
          type: string
        price:
          type: number
        quantity:
          type: integer
    Order:
      type: object
      properties:
        order_id:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/CartItem"
        total:
          type: number
        status:
          type: string
        created_at:
          type: string
          format: date-time
        customer_info:
          type: object
        payment_info:
          type: object
          properties:
            method:
              type: string
            status:
              type: string
            transaction_id:
              type: string
        notes:
          type: array
          items:
            type: string
paths:
  /api/menu/categories:
    get:
      summary: Get all menu categories
      tags:
        - Menu
      responses:
        "200":
          description: List of menu categories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/menu/items:
    get:
      summary: Get menu items with optional filtering
      tags:
        - Menu
      parameters:
        - in: query
          name: category
          schema:
            type: string
          description: Filter by category
        - in: query
          name: dietary_preference
          schema:
            type: string
            enum:
              - vegetarian
              - vegan
              - gluten_free
          description: Filter by dietary preference
        - in: query
          name: max_price
          schema:
            type: number
          description: Maximum price filter
        - in: query
          name: exclude_allergens
          schema:
            type: array
            items:
              type: string
          description: Allergens to exclude (comma-separated)
      responses:
        "200":
          description: List of menu items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MenuItem"
  /api/menu/items/{id}:
    get:
      summary: Get menu item details by ID
      tags:
        - Menu
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Menu item ID
      responses:
        "200":
          description: Menu item details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MenuItem"
        "404":
          description: Item not found
  /api/cart:
    post:
      summary: Create a new shopping cart
      tags:
        - Cart
      responses:
        "201":
          description: Cart created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_id:
                    type: string
                  cart:
                    type: array
                    items:
                      $ref: "#/components/schemas/CartItem"
  /api/cart/{session_id}:
    get:
      summary: Get cart contents
      tags:
        - Cart
      parameters:
        - in: path
          name: session_id
          required: true
          schema:
            type: string
          description: Cart session ID
      responses:
        "200":
          description: Cart contents
          content:
            application/json:
              schema:
                type: object
                properties:
                  cart:
                    type: array
                    items:
                      $ref: "#/components/schemas/CartItem"
                  total:
                    type: number
        "404":
          description: Session not found
  /api/cart/{session_id}/items:
    post:
      summary: Add item to cart
      tags:
        - Cart
      parameters:
        - in: path
          name: session_id
          required: true
          schema:
            type: string
          description: Cart session ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - item_id
              properties:
                item_id:
                  type: string
                quantity:
                  type: integer
                  default: 1
      responses:
        "200":
          description: Item added to cart
          content:
            application/json:
              schema:
                type: object
                properties:
                  cart:
                    type: array
                    items:
                      $ref: "#/components/schemas/CartItem"
                  total:
                    type: number
        "404":
          description: Session or item not found
  /api/cart/{session_id}/items/{item_id}:
    delete:
      summary: Remove item from cart
      tags:
        - Cart
      parameters:
        - in: path
          name: session_id
          required: true
          schema:
            type: string
          description: Cart session ID
        - in: path
          name: item_id
          required: true
          schema:
            type: string
          description: Item ID to remove
      responses:
        "200":
          description: Item removed from cart
          content:
            application/json:
              schema:
                type: object
                properties:
                  cart:
                    type: array
                    items:
                      $ref: "#/components/schemas/CartItem"
                  total:
                    type: number
        "404":
          description: Session not found
  /api/orders:
    post:
      summary: Checkout and create order
      tags:
        - Orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - session_id
              properties:
                session_id:
                  type: string
                customer_info:
                  type: object
                payment_info:
                  type: object
      responses:
        "201":
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "400":
          description: Invalid request (empty cart or invalid session)
    get:
      summary: List all orders
      tags:
        - Orders
      responses:
        "200":
          description: List of all orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
  /api/orders/{order_id}:
    get:
      summary: Get order details
      tags:
        - Orders
      parameters:
        - in: path
          name: order_id
          required: true
          schema:
            type: string
          description: Order ID
      responses:
        "200":
          description: Order details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "404":
          description: Order not found
  /api/orders/{order_id}/notes:
    post:
      summary: Add note to order
      tags:
        - Orders
      parameters:
        - in: path
          name: order_id
          required: true
          schema:
            type: string
          description: Order ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - note
              properties:
                note:
                  type: string
      responses:
        "200":
          description: Note added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  notes:
                    type: array
                    items:
                      type: string
        "404":
          description: Order not found
tags: []
